#!/bin/bash

red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
no_color='\033[0m'

echo -e "\n${yellow}Executing pre-commit hook...${no_color}\n"

FILES_PATTERN='\.(js|jsx|ts|tsx)(\..+)?$'
FORBIDDEN='console\.[clear|dir|log|info|warn|error]'

# Skip check if ALLOW_CONSOLE=true
if [ "$ALLOW_CONSOLE" != "true" ]; then
  if git diff --cached --name-only | \
      grep -E "$FILES_PATTERN" | \
      xargs grep --with-filename -n "$FORBIDDEN" | \
      grep -v '//';
  then
      echo -e "\n${red}COMMIT REJECTED! Found console. Please remove them before committing.\n${no_color}"
      exit 1;
  fi
else
  echo -e "${yellow}Skipping console check due to ALLOW_CONSOLE flag.${no_color}"
fi

echo -e "${green}Git pre-commit hook was successful!${no_color}\n"

npx lint-staged
